### ISSUE TITLE
Default thread value

### ISSUE THREAD

**Issue by pditommaso** [jorgee/parallel_data_processor#1]
Hi, thanks for creating this project. To make it easier for the end-user, what could be a sensitive value for the number of threads if the user does not specify it? 

https://github.com/jorgee/parallel_data_processor/blob/main/src/main/java/es/jea/processor/DataProcessingFramework.java#L66-L67

**Comment by jorgee** [comment]
Code modified to get default number of threads form the system.

**Comment by pditommaso** [comment]
Hi, was trying this but I'm not getting the expected behaviour: 

```
» ./run.sh test_data/input.csv out.csv
Incorrect number of arguments <inputFile> <outputFile> <numThreads>
```

**Comment by jorgee** [comment]
Have you remembered to pull the latest version and rebuild the jar with "mvn clean package"? In the code, numThreads is now mark as optional "[<numThreads>]" and in the log it is still appearing as a mandatory parameter <numThreads>. I think something is not updated in your test.

**Comment by pditommaso** [comment]
You are right 👍
